### ISSUE TITLE
Interesting issue with a corrected word and a punctuation mark

### ISSUE THREAD

**Issue by amirsol81** [ultrasound1372/NVDA-IBMTTS-Driver#16] opened 2020-08-09 19:56 UTC
@ultrasound1372 Few days ago I corrected the word "mulan" via ENURoot.dic. However, IBMTTS still mishandles it when it's encountered as part of the title of the following page -- please open it: https://www.npr.org/2020/08/05/899230689/what-mulans-disney-premiere-means-for-the-film-industry?utm_medium=RSS&utm_campaign=morningedition
It seems that the presence of two apostrophes, one after the letter s, Mulan's', is the culprit. Disabling the Short pauses feature doesn't fix the issue so it might be something related to the internals of the engine itself. Do you think something could be done about it?
Thanks.

**Comment by ultrasound1372** [comment] 2020-08-18 00:37
This is related to ECI itself, as I have an app that allows me to access the API in its most raw form I have confirmed that it will pronounce it correctly when encountering "mulan's" and "mulans'", but not "mulan's'." I have no idea what it would be thinking that string is made of, but how often do you really see a double apostrophe around an s like that? Especially on words in the dictionary? I don't believe I could merge some sort of hackish workaround into the driver due to this rarity. It could be fixed on your end with NVDA dictionaries if it is a major problem to you with the text you read.

**Comment by amirsol81** [comment] 2020-08-18 03:50
@ultrasound1372 Thanks for the explanation. It's something I encounter rather sporadically on news-oriented websites. But it's not a big deal.

**Closed as completed** 2020-08-18 03:50 UTC
